/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as StatisticsRouteImport } from './routes/statistics';
import { Route as IndexRouteImport } from './routes/index';
import { Route as StatisticsReleasedateRouteImport } from './routes/statistics/releasedate';
import { Route as StatisticsGenreRouteImport } from './routes/statistics/genre';
import { Route as MovieMovieIdIndexRouteImport } from './routes/movie.$movieId.index';

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport
} as any);
const StatisticsReleasedateRoute = StatisticsReleasedateRouteImport.update({
  id: '/releasedate',
  path: '/releasedate',
  getParentRoute: () => StatisticsRoute
} as any);
const StatisticsGenreRoute = StatisticsGenreRouteImport.update({
  id: '/genre',
  path: '/genre',
  getParentRoute: () => StatisticsRoute
} as any);
const MovieMovieIdIndexRoute = MovieMovieIdIndexRouteImport.update({
  id: '/movie/$movieId/',
  path: '/movie/$movieId/',
  getParentRoute: () => rootRouteImport
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/statistics': typeof StatisticsRouteWithChildren;
  '/statistics/genre': typeof StatisticsGenreRoute;
  '/statistics/releasedate': typeof StatisticsReleasedateRoute;
  '/movie/$movieId': typeof MovieMovieIdIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/statistics': typeof StatisticsRouteWithChildren;
  '/statistics/genre': typeof StatisticsGenreRoute;
  '/statistics/releasedate': typeof StatisticsReleasedateRoute;
  '/movie/$movieId': typeof MovieMovieIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/statistics': typeof StatisticsRouteWithChildren;
  '/statistics/genre': typeof StatisticsGenreRoute;
  '/statistics/releasedate': typeof StatisticsReleasedateRoute;
  '/movie/$movieId/': typeof MovieMovieIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/statistics'
    | '/statistics/genre'
    | '/statistics/releasedate'
    | '/movie/$movieId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/statistics'
    | '/statistics/genre'
    | '/statistics/releasedate'
    | '/movie/$movieId';
  id:
    | '__root__'
    | '/'
    | '/statistics'
    | '/statistics/genre'
    | '/statistics/releasedate'
    | '/movie/$movieId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  StatisticsRoute: typeof StatisticsRouteWithChildren;
  MovieMovieIdIndexRoute: typeof MovieMovieIdIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics';
      path: '/statistics';
      fullPath: '/statistics';
      preLoaderRoute: typeof StatisticsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/statistics/releasedate': {
      id: '/statistics/releasedate';
      path: '/releasedate';
      fullPath: '/statistics/releasedate';
      preLoaderRoute: typeof StatisticsReleasedateRouteImport;
      parentRoute: typeof StatisticsRoute;
    };
    '/statistics/genre': {
      id: '/statistics/genre';
      path: '/genre';
      fullPath: '/statistics/genre';
      preLoaderRoute: typeof StatisticsGenreRouteImport;
      parentRoute: typeof StatisticsRoute;
    };
    '/movie/$movieId/': {
      id: '/movie/$movieId/';
      path: '/movie/$movieId';
      fullPath: '/movie/$movieId';
      preLoaderRoute: typeof MovieMovieIdIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface StatisticsRouteChildren {
  StatisticsGenreRoute: typeof StatisticsGenreRoute;
  StatisticsReleasedateRoute: typeof StatisticsReleasedateRoute;
}

const StatisticsRouteChildren: StatisticsRouteChildren = {
  StatisticsGenreRoute: StatisticsGenreRoute,
  StatisticsReleasedateRoute: StatisticsReleasedateRoute
};

const StatisticsRouteWithChildren = StatisticsRoute._addFileChildren(
  StatisticsRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatisticsRoute: StatisticsRouteWithChildren,
  MovieMovieIdIndexRoute: MovieMovieIdIndexRoute
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
