/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieMovieIdIndexRouteImport } from './routes/movie.$movieId.index'
import { Route as MovieMovieIdEditRouteImport } from './routes/movie_/$movieId/edit'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdIndexRoute = MovieMovieIdIndexRouteImport.update({
  id: '/movie/$movieId/',
  path: '/movie/$movieId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdEditRoute = MovieMovieIdEditRouteImport.update({
  id: '/movie_/$movieId/edit',
  path: '/movie/$movieId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/statistics': typeof StatisticsRoute
  '/movie/$movieId/edit': typeof MovieMovieIdEditRoute
  '/movie/$movieId': typeof MovieMovieIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/statistics': typeof StatisticsRoute
  '/movie/$movieId/edit': typeof MovieMovieIdEditRoute
  '/movie/$movieId': typeof MovieMovieIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/statistics': typeof StatisticsRoute
  '/movie_/$movieId/edit': typeof MovieMovieIdEditRoute
  '/movie/$movieId/': typeof MovieMovieIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/statistics' | '/movie/$movieId/edit' | '/movie/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/statistics' | '/movie/$movieId/edit' | '/movie/$movieId'
  id:
    | '__root__'
    | '/'
    | '/statistics'
    | '/movie_/$movieId/edit'
    | '/movie/$movieId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatisticsRoute: typeof StatisticsRoute
  MovieMovieIdEditRoute: typeof MovieMovieIdEditRoute
  MovieMovieIdIndexRoute: typeof MovieMovieIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId/': {
      id: '/movie/$movieId/'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie_/$movieId/edit': {
      id: '/movie_/$movieId/edit'
      path: '/movie/$movieId/edit'
      fullPath: '/movie/$movieId/edit'
      preLoaderRoute: typeof MovieMovieIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatisticsRoute: StatisticsRoute,
  MovieMovieIdEditRoute: MovieMovieIdEditRoute,
  MovieMovieIdIndexRoute: MovieMovieIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
